// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using knkwebapi_v2.Properties;

#nullable disable

namespace knkwebapi_v2.Migrations
{
    [DbContext(typeof(KnKDbContext))]
    [Migration("20251206145223_FormFieldElementType")]
    partial class FormFieldElementType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("knkwebapi_v2.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItemtypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowEntry")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowExit")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WgRegionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FieldValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("FormFieldId")
                        .HasColumnType("int");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormFieldId");

                    b.ToTable("FieldValidations");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConfigurationGuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("EntityTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StepOrderJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationGuid")
                        .IsUnique();

                    b.HasIndex("EntityTypeName");

                    b.ToTable("FormConfigurations");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("longtext");

                    b.Property<string>("DependencyConditionJson")
                        .HasColumnType("longtext");

                    b.Property<int?>("DependsOnFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("ElementType")
                        .HasColumnType("int");

                    b.Property<string>("EnumType")
                        .HasColumnType("longtext");

                    b.Property<Guid>("FieldGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<int?>("FormStepId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectType")
                        .HasColumnType("longtext");

                    b.Property<string>("Placeholder")
                        .HasColumnType("longtext");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Required")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SourceFieldId")
                        .HasColumnType("int");

                    b.Property<int?>("SubConfigurationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnFieldId");

                    b.HasIndex("FormStepId");

                    b.HasIndex("IsReusable");

                    b.HasIndex("SubConfigurationId");

                    b.ToTable("FormFields");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FieldOrderJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FormConfigurationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SourceStepId")
                        .HasColumnType("int");

                    b.Property<Guid>("StepGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FormConfigurationId");

                    b.HasIndex("IsReusable");

                    b.ToTable("FormSteps");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormSubmissionProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllStepsDataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentStepDataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("int");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("FormConfigurationId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentProgressId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgressGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormConfigurationId");

                    b.HasIndex("ParentProgressId");

                    b.HasIndex("UserId");

                    b.ToTable("FormSubmissionProgresses");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.StepCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionLogicJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("FormStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormStepId");

                    b.ToTable("StepConditions");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("cash")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Category", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FieldValidation", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.FormField", "FormField")
                        .WithMany("Validations")
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormField");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormField", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.FormField", "DependsOnField")
                        .WithMany("DependentFields")
                        .HasForeignKey("DependsOnFieldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("knkwebapi_v2.Models.FormStep", "FormStep")
                        .WithMany("Fields")
                        .HasForeignKey("FormStepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("knkwebapi_v2.Models.FormConfiguration", "SubConfiguration")
                        .WithMany()
                        .HasForeignKey("SubConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DependsOnField");

                    b.Navigation("FormStep");

                    b.Navigation("SubConfiguration");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormStep", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.FormConfiguration", "FormConfiguration")
                        .WithMany("Steps")
                        .HasForeignKey("FormConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FormConfiguration");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormSubmissionProgress", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.FormConfiguration", "FormConfiguration")
                        .WithMany("SubmissionProgresses")
                        .HasForeignKey("FormConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knkwebapi_v2.Models.FormSubmissionProgress", "ParentProgress")
                        .WithMany()
                        .HasForeignKey("ParentProgressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("knkwebapi_v2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormConfiguration");

                    b.Navigation("ParentProgress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.StepCondition", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.FormStep", "FormStep")
                        .WithMany("StepConditions")
                        .HasForeignKey("FormStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormStep");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormConfiguration", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("SubmissionProgresses");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormField", b =>
                {
                    b.Navigation("DependentFields");

                    b.Navigation("Validations");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormStep", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("StepConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
