// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using knkwebapi_v2.Properties;

#nullable disable

namespace knkwebapi_v2.Migrations
{
    [DbContext(typeof(KnKDbContext))]
    [Migration("20251213161927_AddIsEditableInDisplayToDisplayField")]
    partial class AddIsEditableInDisplayToDisplayField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DistrictStreet", b =>
                {
                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("StreetId")
                        .HasColumnType("int");

                    b.HasKey("DistrictId", "StreetId");

                    b.HasIndex("StreetId");

                    b.ToTable("DistrictStreet");
                });

            modelBuilder.Entity("TownStreet", b =>
                {
                    b.Property<int>("StreetId")
                        .HasColumnType("int");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.HasKey("StreetId", "TownId");

                    b.HasIndex("TownId");

                    b.ToTable("TownStreet");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IconMaterialRefId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("IconMaterialRefId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("knkwebapi_v2.Models.DisplayConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConfigurationGuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EntityTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SectionOrderJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsDraft")
                        .HasDatabaseName("IX_DisplayConfiguration_IsDraft");

                    b.HasIndex("EntityTypeName", "IsDefault")
                        .HasDatabaseName("IX_DisplayConfiguration_EntityType_Default");

                    b.ToTable("DisplayConfigurations");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.DisplayField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("DisplaySectionId")
                        .HasColumnType("int");

                    b.Property<Guid>("FieldGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("FieldName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FieldType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsEditableInDisplay")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLinkedToSource")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RelatedEntityPropertyName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RelatedEntityTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("SourceFieldId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateText")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DisplaySectionId");

                    b.HasIndex("IsReusable")
                        .HasDatabaseName("IX_DisplayField_IsReusable");

                    b.ToTable("DisplayFields");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.DisplaySection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionButtonsConfigJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("DisplayConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("FieldOrderJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCollection")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLinkedToSource")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ParentSectionId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityPropertyName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RelatedEntityTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SectionGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("SourceSectionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayConfigurationId");

                    b.HasIndex("IsReusable")
                        .HasDatabaseName("IX_DisplaySection_IsReusable");

                    b.HasIndex("ParentSectionId")
                        .HasDatabaseName("IX_DisplaySection_ParentSectionId");

                    b.ToTable("DisplaySections");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowEntry")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowExit")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WgRegionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("domains", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FieldValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("FormFieldId")
                        .HasColumnType("int");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormFieldId");

                    b.ToTable("FieldValidations");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConfigurationGuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("EntityTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StepOrderJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationGuid")
                        .IsUnique();

                    b.HasIndex("EntityTypeName");

                    b.ToTable("FormConfigurations");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("longtext");

                    b.Property<string>("DependencyConditionJson")
                        .HasColumnType("longtext");

                    b.Property<int?>("DependsOnFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("ElementType")
                        .HasColumnType("int");

                    b.Property<string>("EnumType")
                        .HasColumnType("longtext");

                    b.Property<Guid>("FieldGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<int?>("FormStepId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLinkedToSource")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectType")
                        .HasColumnType("longtext");

                    b.Property<string>("Placeholder")
                        .HasColumnType("longtext");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Required")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SourceFieldId")
                        .HasColumnType("int");

                    b.Property<int?>("SubConfigurationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnFieldId");

                    b.HasIndex("FormStepId");

                    b.HasIndex("IsReusable");

                    b.HasIndex("SubConfigurationId");

                    b.ToTable("FormFields");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FieldOrderJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FormConfigurationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLinkedToSource")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SourceStepId")
                        .HasColumnType("int");

                    b.Property<Guid>("StepGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FormConfigurationId");

                    b.HasIndex("IsReusable");

                    b.ToTable("FormSteps");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormSubmissionProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllStepsDataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentStepDataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("int");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("FormConfigurationId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentProgressId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgressGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormConfigurationId");

                    b.HasIndex("ParentProgressId");

                    b.HasIndex("UserId");

                    b.ToTable("FormSubmissionProgresses");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<float>("Pitch")
                        .HasColumnType("float");

                    b.Property<string>("World")
                        .HasColumnType("longtext");

                    b.Property<double>("X")
                        .HasColumnType("double");

                    b.Property<double>("Y")
                        .HasColumnType("double");

                    b.Property<float>("Yaw")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("double");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("knkwebapi_v2.Models.MinecraftBlockRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockStateString")
                        .HasColumnType("longtext");

                    b.Property<string>("LogicalType")
                        .HasColumnType("longtext");

                    b.Property<string>("NamespaceKey")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("minecraftblockrefs", (string)null);
                });

            modelBuilder.Entity("knkwebapi_v2.Models.MinecraftMaterialRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LegacyName")
                        .HasColumnType("longtext");

                    b.Property<string>("NamespaceKey")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("NamespaceKey")
                        .IsUnique();

                    b.ToTable("minecraftmaterialrefs", (string)null);
                });

            modelBuilder.Entity("knkwebapi_v2.Models.StepCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionLogicJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("FormStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormStepId");

                    b.ToTable("StepConditions");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("streets", (string)null);
                });

            modelBuilder.Entity("knkwebapi_v2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("cash")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("knkwebapi_v2.Models.District", b =>
                {
                    b.HasBaseType("knkwebapi_v2.Models.Domain");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.HasIndex("TownId");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Structure", b =>
                {
                    b.HasBaseType("knkwebapi_v2.Models.Domain");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<int>("StreetId")
                        .HasColumnType("int");

                    b.HasIndex("DistrictId");

                    b.HasIndex("StreetId");

                    b.ToTable("structures", (string)null);
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Town", b =>
                {
                    b.HasBaseType("knkwebapi_v2.Models.Domain");

                    b.ToTable("towns", (string)null);
                });

            modelBuilder.Entity("DistrictStreet", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knkwebapi_v2.Models.Street", null)
                        .WithMany()
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TownStreet", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.Street", null)
                        .WithMany()
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knkwebapi_v2.Models.Town", null)
                        .WithMany()
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Category", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.MinecraftMaterialRef", "IconMaterialRef")
                        .WithMany()
                        .HasForeignKey("IconMaterialRefId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("knkwebapi_v2.Models.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("IconMaterialRef");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.DisplayField", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.DisplaySection", "DisplaySection")
                        .WithMany("Fields")
                        .HasForeignKey("DisplaySectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DisplaySection");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.DisplaySection", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.DisplayConfiguration", "DisplayConfiguration")
                        .WithMany("Sections")
                        .HasForeignKey("DisplayConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("knkwebapi_v2.Models.DisplaySection", "ParentSection")
                        .WithMany("SubSections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DisplayConfiguration");

                    b.Navigation("ParentSection");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Domain", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.Location", "Location")
                        .WithOne()
                        .HasForeignKey("knkwebapi_v2.Models.Domain", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FieldValidation", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.FormField", "FormField")
                        .WithMany("Validations")
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormField");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormField", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.FormField", "DependsOnField")
                        .WithMany("DependentFields")
                        .HasForeignKey("DependsOnFieldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("knkwebapi_v2.Models.FormStep", "FormStep")
                        .WithMany("Fields")
                        .HasForeignKey("FormStepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("knkwebapi_v2.Models.FormConfiguration", "SubConfiguration")
                        .WithMany()
                        .HasForeignKey("SubConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DependsOnField");

                    b.Navigation("FormStep");

                    b.Navigation("SubConfiguration");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormStep", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.FormConfiguration", "FormConfiguration")
                        .WithMany("Steps")
                        .HasForeignKey("FormConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FormConfiguration");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormSubmissionProgress", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.FormConfiguration", "FormConfiguration")
                        .WithMany("SubmissionProgresses")
                        .HasForeignKey("FormConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knkwebapi_v2.Models.FormSubmissionProgress", "ParentProgress")
                        .WithMany()
                        .HasForeignKey("ParentProgressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("knkwebapi_v2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormConfiguration");

                    b.Navigation("ParentProgress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.StepCondition", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.FormStep", "FormStep")
                        .WithMany("StepConditions")
                        .HasForeignKey("FormStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormStep");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.District", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.Domain", null)
                        .WithOne()
                        .HasForeignKey("knkwebapi_v2.Models.District", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knkwebapi_v2.Models.Town", "Town")
                        .WithMany("Districts")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Town");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Structure", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.District", "District")
                        .WithMany("Structures")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("knkwebapi_v2.Models.Domain", null)
                        .WithOne()
                        .HasForeignKey("knkwebapi_v2.Models.Structure", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("knkwebapi_v2.Models.Street", "Street")
                        .WithMany("Structures")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Street");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Town", b =>
                {
                    b.HasOne("knkwebapi_v2.Models.Domain", null)
                        .WithOne()
                        .HasForeignKey("knkwebapi_v2.Models.Town", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("knkwebapi_v2.Models.DisplayConfiguration", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.DisplaySection", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("SubSections");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormConfiguration", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("SubmissionProgresses");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormField", b =>
                {
                    b.Navigation("DependentFields");

                    b.Navigation("Validations");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.FormStep", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("StepConditions");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Street", b =>
                {
                    b.Navigation("Structures");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.District", b =>
                {
                    b.Navigation("Structures");
                });

            modelBuilder.Entity("knkwebapi_v2.Models.Town", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
